[build]
  base = "frontend"
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "22"
  VITE_API_URL = "https://bharatmart-2.onrender.com/api"
  VITE_MEDIA_URL = "https://bharatmart-2.onrender.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
